/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Calisthenics Workout
 * OpenAPI spec version: 0.0.0
 */
import type {
  UserProfileCreate422,
  UserProfileModelCreateUserProfileRequest,
  UserProfileModelUserProfile,
  UserProfileShow404
} from '../calisthenicsWorkout.schemas';


export type userProfileShowResponse200 = {
  data: UserProfileModelUserProfile
  status: 200
}

export type userProfileShowResponse404 = {
  data: UserProfileShow404
  status: 404
}

export type userProfileShowResponseSuccess = (userProfileShowResponse200) & {
  headers: Headers;
};
export type userProfileShowResponseError = (userProfileShowResponse404) & {
  headers: Headers;
};

export type userProfileShowResponse = (userProfileShowResponseSuccess | userProfileShowResponseError)

export const getUserProfileShowUrl = () => {


  

  return `/api/v1/user_profile`
}

export const userProfileShow = async ( options?: RequestInit): Promise<userProfileShowResponse> => {
  
  const res = await fetch(getUserProfileShowUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: userProfileShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as userProfileShowResponse
}
  

export type userProfileCreateResponse201 = {
  data: UserProfileModelUserProfile
  status: 201
}

export type userProfileCreateResponse422 = {
  data: UserProfileCreate422
  status: 422
}

export type userProfileCreateResponseSuccess = (userProfileCreateResponse201) & {
  headers: Headers;
};
export type userProfileCreateResponseError = (userProfileCreateResponse422) & {
  headers: Headers;
};

export type userProfileCreateResponse = (userProfileCreateResponseSuccess | userProfileCreateResponseError)

export const getUserProfileCreateUrl = () => {


  

  return `/api/v1/user_profile`
}

export const userProfileCreate = async (userProfileModelCreateUserProfileRequest: UserProfileModelCreateUserProfileRequest, options?: RequestInit): Promise<userProfileCreateResponse> => {
  
  const res = await fetch(getUserProfileCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userProfileModelCreateUserProfileRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: userProfileCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as userProfileCreateResponse
}
  

