openapi: 3.1.0
info:
  title: Calisthenics Workout
  version: 0.0.0
tags: []
paths:
  /api/v1/user_profile:
    get:
      operationId: UserProfile_show
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileModel.UserProfile'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
    post:
      operationId: UserProfile_create
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileModel.UserProfile'
        '422':
          description: Client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileModel.CreateUserProfileRequest'
components:
  schemas:
    UserProfileModel.CreateUserProfileRequest:
      type: object
      required:
        - last_name
        - first_name
      properties:
        last_name:
          type: string
        first_name:
          type: string
        height:
          type: integer
          format: int32
        weight:
          type: number
          format: float
        date_of_birth:
          type: string
          format: date
        avatar:
          type: string
          contentEncoding: base64
    UserProfileModel.UserProfile:
      type: object
      required:
        - id
        - better_auth_user_id
        - last_name
        - first_name
        - height
        - weight
        - date_of_birth
        - avatar_url
      properties:
        id:
          type: integer
          format: int32
        better_auth_user_id:
          type: string
        last_name:
          type: string
        first_name:
          type: string
        height:
          anyOf:
            - type: integer
              format: int32
            - type: 'null'
        weight:
          anyOf:
            - type: number
              format: float
            - type: 'null'
        date_of_birth:
          anyOf:
            - type: string
              format: date
            - type: 'null'
        avatar_url:
          anyOf:
            - type: string
            - type: 'null'
