openapi: 3.1.0
info:
  title: Calisthenics Workout
  version: 0.0.0
tags: []
paths:
  /sample:
    get:
      operationId: sample
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleModel.Sample'
components:
  schemas:
    SampleModel.Language:
      type: string
      enum:
        - python
        - typescript
        - ruby
    SampleModel.Pref:
      type: string
      enum:
        - tokyo
        - osaka
        - kyoto
    SampleModel.Sample:
      type: object
      required:
        - id
        - name
        - language
        - preference
      properties:
        id:
          type: string
        name:
          type: string
        language:
          $ref: '#/components/schemas/SampleModel.Language'
        preference:
          $ref: '#/components/schemas/SampleModel.Pref'
