/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Calisthenics Workout
 * OpenAPI spec version: 0.0.0
 */
export interface UserProfileModelCreateUserProfileRequest {
  last_name: string;
  first_name: string;
  height?: number;
  weight?: number;
  date_of_birth?: string;
  avatar?: string;
}

export interface UserProfileModelUpdateUserProfileRequest {
  last_name?: string;
  first_name?: string;
  height?: number;
  weight?: number;
  date_of_birth?: string;
  avatar?: string;
}

export interface UserProfileModelUserProfile {
  id: number;
  better_auth_user_id: string;
  last_name: string;
  first_name: string;
  /** @nullable */
  height: number | null;
  /** @nullable */
  weight: number | null;
  /** @nullable */
  date_of_birth: string | null;
  /** @nullable */
  avatar_url: string | null;
}

export type UserProfileShow404 = {
  error: string;
};

export type UserProfileCreate422 = {
  errors: string[];
};

export type UserProfileUpdate404 = {
  error: string;
};

export type UserProfileUpdate422 = {
  errors: string[];
};

